version: '3.9'
services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=passwrd
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456
  adminer:
    image: adminer
    ports:
      - 8080:8080
  web:
    image: docker.io/bitnami/laravel:9
    volumes:
      - .:/app/
    ports:
      - '9000:8000'
    working_dir: /app  
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./deploy/nginx/nginx.conf :etc/nginx/conf.d/default.conf
  #     - ./public:var/www/public
  #   ports:
  #     - 8080:80
